---
title: "desica testing"
author: "Remko Duursma"
date: "7 September 2017"
output: html_document
---

```{r}
source("functions.R")
library(plantecophys)
library(fitplc)
```


# One simplified diurnal

```{r}

d <- diurnal_sim()

eleaf <- 1.5 * d$PPFD / max(d$PPFD) + 0.1
n <- length(eleaf)

kp <- 2
Cl <- 400
Cs <- 4000
timestep <- 15*60
AL <- 10

psist <- psil <- Jrs <- Jsl <- c()

psis <- -0.2

psil[1] <- -0.01
psist[1] <- -0.005


for(i in 2:n){
  bp <- (AL * 2 * kp*psist[i-1] - AL*eleaf[i])/Cl
  ap <- -(AL * 2 * kp / Cl)
  psil[i] <- ((ap*psil[i-1] + bp)*exp(ap*timestep) - bp)/ap
  
  # flux from stem to leaf= change in leaf storage, plus transpiration
  Jsl[i] <- (psil[i] - psil[i-1]) * Cl / timestep + AL*eleaf[i]
  
  # new stem water potential
  # again follow Xu
  bp <- (AL * 2 * kp * psis - Jsl[i])/Cs
  ap <- -(AL * 2 * kp / Cs)
  
  psist[i] <- ((ap*psist[i-1] + bp)*exp(ap*timestep) - bp)/ap
  
  # flux from soil to stem = change in stem storage, plus Jrl
  Jrs[i] <- (psist[i] - psist[i-1])*Cs/timestep + Jsl[i]
}

plot(1:n, psil, type='l')
lines(psist, lty=3)

plot(eleaf, psil, type='l')

```


# Time series

```{r}
m <- make_simdfr(ndays=10)
m$psis <- seq(0, -3, length=nrow(m))


eleaf <- 1.5 * sqrt(m$VPD)
n <- length(eleaf)

kp <- 2
Cl <- 400
Cs <- 4000
timestep <- 15*60
AL <- 10

psist <- psil <- Jrs <- Jsl <- c()

psis <- -0.2

psil[1] <- -0.01
psist[1] <- -0.005


for(i in 2:n){
  bp <- (AL * 2 * kp*psist[i-1] - AL*eleaf[i])/Cl
  ap <- -(AL * 2 * kp / Cl)
  psil[i] <- ((ap*psil[i-1] + bp)*exp(ap*timestep) - bp)/ap
  
  # flux from stem to leaf= change in leaf storage, plus transpiration
  Jsl[i] <- (psil[i] - psil[i-1]) * Cl / timestep + AL*eleaf[i]
  
  # new stem water potential
  # again follow Xu
  bp <- (AL * 2 * kp * psis - Jsl[i])/Cs
  ap <- -(AL * 2 * kp / Cs)
  
  psist[i] <- ((ap*psist[i-1] + bp)*exp(ap*timestep) - bp)/ap
  
  # flux from soil to stem = change in stem storage, plus Jrl
  Jrs[i] <- (psist[i] - psist[i-1])*Cs/timestep + Jsl[i]
}

plot(1:n, psil, type='l')
lines(psist, lty=3)


```


# towards full model

```{r}


  psie <- -0.8*1E-03
  psiv <- -2
  sf <- 8
  g1 <- 5
  
  b <- 6
  
  p50 <- -4
  s50 <- 30

  m <- make_simdfr(ndays=10)
  m$psis <- seq(0, -3, length=nrow(m))
  
  kpsat <- 2
  Cl <- 400
  Cs <- 4000
  timestep <- 15*60
  AL <- 10
  
  eleaf <- psist <- psil <- Jrs <- Jsl <- kp <- c()
  
  psis <- -0.2
  
  kp[1] <- kpsat
  psil[1] <- -0.01
  psist[1] <- -0.005


for(i in 2:n){
  
  kp[i] <- kpsat * fweibull(abs(psist[i-1]), s50, abs(p50))
  
  fsig_tuzet <- function(psil, psiv, sf){
    (1 + exp(sf*psiv)) / (1 + exp(sf*(psiv - psil)))
  }
  
  # packageVersion("plantecophys") >= "1.2-6"
  # p <- Photosyn(VPD=VPD, gsmodel="BBdefine", 
  #               BBmult=(g1/Ca)*fsig_tuzet(psil, psiv, sf), 
  #               Tleaf=Tair, g1=g1)
  eleaf[i] <- 2 * fsig_tuzet(psil[i-1], psiv=psiv, sf=sf) + 0.2
  
  
  bp <- (AL * 2 * kp[i]*psist[i-1] - AL*eleaf[i])/Cl
  ap <- -(AL * 2 * kp[i] / Cl)
  psil[i] <- ((ap*psil[i-1] + bp)*exp(ap*timestep) - bp)/ap
  
  # flux from stem to leaf= change in leaf storage, plus transpiration
  Jsl[i] <- (psil[i] - psil[i-1]) * Cl / timestep + AL*eleaf[i]
  
  # new stem water potential
  # again follow Xu
  bp <- (AL * 2 * kp[i] * m$psis[i] - Jsl[i])/Cs
  ap <- -(AL * 2 * kp[i] / Cs)
  
  psist[i] <- ((ap*psist[i-1] + bp)*exp(ap*timestep) - bp)/ap
  
  # flux from soil to stem = change in stem storage, plus Jrl
  Jrs[i] <- (psist[i] - psist[i-1])*Cs/timestep + Jsl[i]
}


  plot(psil, type='l')
  lines(psist, lty=3)
                      
  plot(Jsl, ylim=c(0,max(Jsl, na.rm=T)), type='l')
  lines(Jrs, lty=3)
  lines(eleaf*AL, col="blue2")
```



# fuller model


```{r}

  psie <- -0.8*1E-03
  psiv <- -1.7
  sf <- 8
  g1 <- 5
  Ca <- 400
  
  b <- 6
  
  p50 <- -2
  s50 <- 30

  m <- make_simdfr(ndays=30)
  m$psis <- seq(0, -2.5, length=nrow(m))
  n <- nrow(m)
  kpsat <- 2
  Cl <- 40000
  Cs <- 40000
  timestep <- 15*60
  AL <- 10
  gmin <- 10
    
  eleaf <- psist <- psil <- Jrs <- Jsl <- kp <- ks <- c()
  psil2 <- c()
  psis <- -0.2
  
  kp[1] <- kpsat
  psil[1] <- -0.01
  psist[1] <- -0.005

    ks <- ksoil_fun(m$psis, Ksat=100, psie, b, LAI=2, soildepth=1)


for(i in 2:n){
  
  kp[i] <- kpsat * fweibull(abs(psist[i-1]), s50, abs(p50))

  fsig_tuzet <- function(psil, psiv, sf){
    (1 + exp(sf*psiv)) / (1 + exp(sf*(psiv - psil)))
  }
  
  # packageVersion("plantecophys") >= "1.2-6"
  # p <- Photosyn(VPD=m$VPD[i], gsmodel="BBdefine",
  #               BBmult=(g1/Ca)*fsig_tuzet(psil[i-1], psiv, sf),
  #               Tleaf=m$Tair[i], g1=g1)
  p <- PhotosynTuzet(VPD=m$VPD[i], PPFD=m$PPFD[i], g1=g1, psis=m$psis[i],
                     Ca=Ca, Tleaf=m$Tair[i], sf=sf, kl=kp[i], psif=psiv)
  eleaf[i] <- p$ELEAF + (m$VPD[i]/101)*gmin  # mmol m-2 s-1
  psil2[i] <- p$PSIL
  bp <- (AL * kp[i]*psist[i-1] - AL*eleaf[i])/Cl
  ap <- -(AL *  kp[i] / Cl)
  psil[i] <- ((ap*psil[i-1] + bp)*exp(ap*timestep) - bp)/ap
  
  # flux from stem to leaf= change in leaf storage, plus transpiration
  Jsl[i] <- (psil[i] - psil[i-1]) * Cl / timestep + AL*eleaf[i]
  
  # new stem water potential
  # again follow Xu
  bp <- (AL * ks[i] * m$psis[i] - Jsl[i])/Cs
  ap <- -(AL * ks[i] / Cs)
  
  psist[i] <- ((ap*psist[i-1] + bp)*exp(ap*timestep) - bp)/ap
  
  # flux from soil to stem = change in stem storage, plus Jrl
  Jrs[i] <- (psist[i] - psist[i-1])*Cs/timestep + Jsl[i]
}


  plot(psil, type='l')
  lines(psist, lty=3)
                      
  plot(Jsl, ylim=c(0,max(Jsl, na.rm=T)), type='l')
  lines(Jrs, lty=3)
  lines(eleaf*AL, col="blue2")
  
  plot(psil, eleaf)
```

